server {
  listen 8080;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  location = /behame {
    return 301 /behame/;
  }

  location /behame/ {
    rewrite ^/behame/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
