apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: running-tracker

resources:
  - namespace.yaml
  - ../../base

configMapGenerator:
  - name: running-tracker-config
    envs:
      - config.env

secretGenerator:
  - name: running-tracker-secret
    envs:
      - secret.env

generatorOptions:
  disableNameSuffixHash: true
  labels:
    app.kubernetes.io/part-of: running-tracker

images:
  - name: running-tracker-backend
    newName: running-tracker-backend
    newTag: local
  - name: running-tracker-frontend
    newName: running-tracker-frontend
    newTag: local
